select [ason], 
[dc], 
[cluster],
 [host], 
 [vm], 
 [powerstate],
  [vm_created_date], 
  [env], 
  [purpose], 
  [vcenter_server], 
  [vcenter], 
  [e2customer], 
  [account], 
  [os_family], 
  [os_major_version], 
  [is_db], 
  [latest_scan_date], 
  [av_installed],
   [isactive], 
   [dc_provider], 
   [product_family], 
   [product_name], 
   [sfdc_product_family], 
   [sfdc_product_name],
    [hub_type], 
    [sfdc_hub_type],
     [department],
      [ps_practice],
       [covered_for_patching],
        [ip], 
        [last_successful_scan_date], 
        [last_patch_update_date], 
        [is_katello_covered], 
        [is_desktop_central_covered], 
        [patch_provenance], 
        [ci_appliance],
         [boot_kernel], 
         [effective_kernel], 
         [is_kcare_covered], 
         [is_eol],
          [numcpu], 
          [memorygb], 
          [provisionedspacegb],
           [missing_patches] 
           from [dbo].[t_exp_patch_vm_coverage];

 data_stream_dataset => "vm-patch-details"
      data_stream_namespace => "vm-patch-coverage"